name: Fetch EC2 Details

on:
  workflow_dispatch:

jobs:
  fetch-ec2-details:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install JQ and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq awscli
          aws --version
          jq --version

      - name: Fetch Running EC2 Instances
        run: |
          aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*]' --output json > ec2_instances.json
          cat ec2_instances.json

      - name: Extract Instance Details Using JQ
        run: |
          INSTANCE_ID=$(jq -r '.[0][0].InstanceId' ec2_instances.json)
          PUBLIC_IP=$(jq -r '.[0][0].PublicIpAddress // "No Public IP"' ec2_instances.json)
          INSTANCE_TYPE=$(jq -r '.[0][0].InstanceType' ec2_instances.json)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "INSTANCE_TYPE=$INSTANCE_TYPE" >> $GITHUB_ENV

      - name: Display Extracted Values
        run: |
          echo "EC2 Instance ID: $INSTANCE_ID"
          echo "Public IP: $PUBLIC_IP"
          echo "Instance Type: $INSTANCE_TYPE"
