name: AWS CLI & JQ Automation

on:
  push:
    branches:
      - main

jobs:
  aws-cli-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI (Latest Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS Access
        run: aws sts get-caller-identity

      - name: Fetch EC2 Instance Details
        run: |
          aws ec2 describe-instances --query "Reservations[].Instances[]" --output json > ec2_instances.json
          cat ec2_instances.json | jq '.[] | {InstanceId: .InstanceId, State: .State.Name, Type: .InstanceType, PublicIP: .PublicIpAddress}'

      - name: Extract EC2 Details Using JQ
        run: |
          INSTANCE_ID=$(jq -r '.[0].InstanceId' ec2_instances.json)
          PUBLIC_IP=$(jq -r '.[0].PublicIpAddress // "No Public IP"' ec2_instances.json)
          INSTANCE_TYPE=$(jq -r '.[0].InstanceType' ec2_instances.json)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "INSTANCE_TYPE=$INSTANCE_TYPE" >> $GITHUB_ENV

      - name: Display Extracted EC2 Details
        run: |
          echo "EC2 Instance ID: $INSTANCE_ID"
          echo "EC2 Public IP: $PUBLIC_IP"
          echo "EC2 Instance Type: $INSTANCE_TYPE"
