name: Fetch IAM Role Details

on:
  workflow_dispatch:

jobs:
  fetch-iam-role:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install JQ and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq awscli
          aws --version
          jq --version

      - name: Install AWS CLI Manually
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: List IAM Roles
        run: |
          aws iam list-roles --query "Roles[*].RoleName" --output json > iam_roles.json
          cat iam_roles.json

      - name: Extract IAM Role Details
        run: |
          ROLE_NAME=$(jq -r '.[0]' iam_roles.json)
          echo "First IAM Role: $ROLE_NAME"

          aws iam get-role --role-name "$ROLE_NAME" --output json > role_details.json
          jq '.' role_details.json

      - name: Extract IAM Policies Using JQ
        run: |
          ROLE_ARN=$(jq -r '.Role.Arn' role_details.json)
          TRUST_POLICY=$(jq -r '.Role.AssumeRolePolicyDocument' role_details.json)

          echo "ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV
          echo "TRUST_POLICY=$TRUST_POLICY" >> $GITHUB_ENV

      - name: Display Extracted IAM Role Details
        run: |
          echo "Role ARN: $ROLE_ARN"
          echo "Trust Policy: $TRUST_POLICY"
