name: Fetch Pod Logs

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig.yaml

      - name: Fetch Pod Logs
        run: |
          POD_NAME="my-pod"
          NAMESPACE="default"
          kubectl logs "$POD_NAME" -n "$NAMESPACE" --timestamps | awk '{print "{\"timestamp\":\""$1"\", \"message\":\""$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10" "$11" "$12" "$13" "$14" "$15"\"}"}' | jq '.'
