name: JSON Parsing with JQ

on: [push]

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Sample JSON
        run: |
          cat <<EOF > products.json
          {
            "products": [
              {"name": "Laptop", "price": 1200, "category": "Electronics"},
              {"name": "Phone", "price": 800, "category": "Electronics"},
              {"name": "Desk", "price": 250, "category": "Furniture"}
            ]
          }
          EOF

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract Product Names
        run: jq '[.products | map(.name)]' products.json

      - name: Filter Expensive Products
        run: jq '[.products[] | select(.price > 500)]' products.json
