name: Extract Kubernetes Pod Details

on:
  workflow_dispatch:

jobs:
  extract-pod-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client  # Verify installation

      - name: Configure Kubeconfig (For AWS EKS)
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure Kubeconfig (For GCP GKE)
        run: |
          gcloud container clusters get-credentials my-cluster --zone us-central1-a
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Kubeconfig (For Azure AKS)
        run: |
          az aks get-credentials --resource-group my-resource-group --name my-cluster
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Kubernetes Connection
        run: |
          kubectl config view  # Check kubeconfig
          kubectl cluster-info  # Verify connection
          kubectl get nodes  # Ensure nodes are running

      - name: Get Pod Details using jq
        run: |
          POD_DETAILS=$(kubectl get pods -n default -o json)
          echo "Raw Pod Details: $POD_DETAILS"  # Debugging

          # Extract pod names and statuses using jq
          POD_NAMES=$(echo "$POD_DETAILS" | jq -r '.items[].metadata.name')
          POD_STATUSES=$(echo "$POD_DETAILS" | jq -r '.items[].status.phase')

          echo "Pods in 'default' namespace:"
          echo "$POD_NAMES" | paste -d ' ' - <(echo "$POD_STATUSES")
