name: Extract Kubernetes Pod Details

on:
  workflow_dispatch:

jobs:
  extract-pod-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client  # Verify installation

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config view

      - name: Get Pod Details using jq
        run: |
          POD_DETAILS=$(kubectl get pods -n default -o json)
          echo "Raw Pod Details: $POD_DETAILS"  # Debugging

          # Extract pod names and statuses using jq
          POD_NAMES=$(echo "$POD_DETAILS" | jq -r '.items[].metadata.name')
          POD_STATUSES=$(echo "$POD_DETAILS" | jq -r '.items[].status.phase')

          echo "Pods in 'default' namespace:"
          echo "$POD_NAMES" | paste -d ' ' - <(echo "$POD_STATUSES")
