name: Terraform Output Extraction

on:
  push:
    branches:
      - main

jobs:
  extract-terraform-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
          unzip terraform_1.6.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Initialize and Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Extract Terraform Outputs
        run: |
          terraform output -json > tf_output.json

          PUBLIC_IP=$(jq -r '.public_ip.value' tf_output.json)
          INSTANCE_ID=$(jq -r '.instance_id.value' tf_output.json)
          INSTANCE_TYPE=$(jq -r '.instance_type.value' tf_output.json)

          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "INSTANCE_TYPE=$INSTANCE_TYPE" >> $GITHUB_ENV

      - name: Print Extracted Variables
        run: |
          echo "Public IP: $PUBLIC_IP"
          echo "Instance ID: $INSTANCE_ID"
          echo "Instance Type: $INSTANCE_TYPE"

      - name: Use Extracted Variables in Another Step
        run: |
          echo "Using extracted Terraform values:"
          echo "Deployed instance with ID $INSTANCE_ID has public IP $PUBLIC_IP"
